SPEECH_FILE = "data/speech.txt"
CHROMA_DIR = "chroma_db"
CHUNK_SIZE = 200
CHUNK_OVERLAP = 50
EMBEDDING_MODEL = "sentence-transformers/all-MiniLM-L6-v2"
OLLAMA_MODEL_NAME = "mistral"
COLLECTION_NAME = "ambedkarspeech"
ALPHA = 0.5
COHERE_RERANK_MODEL = "rerank-english-v2.0"
K=3
VECTOR_K=4