SPEECH_FILE = "data/speech.txt"
CHROMA_DIR = "chroma_db"
CHUNK_SIZE = 350
CHUNK_OVERLAP = 50
EMBEDDING_MODEL = "sentence-transformers/all-MiniLM-L6-v2"
OLLAMA_MODEL_NAME = "mistral"
COLLECTION_NAME = "ambedkarspeech"
ALPHA = 0.5
COHERE_RERANK_MODEL = "rerank-english-v3.0"
K=3
VECTOR_K=4
LLM_MODEL="mistral"
OLLAMA_URL="http://localhost:11434"
NEO4J_URI='neo4j+s://e0e562ea.databases.neo4j.io'
NEO4J_USER="neo4j"
NEO4J_PASS="VFOdD6KTSpkrU_KzA-VS7cScTGIV5-yB7HR5qe3OyGs"